apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-pv
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/managed-by: localk8s-bootstrap
    app.kubernetes.io/part-of: localk8s
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ollama-host-disk
  hostPath:
    path: /mnt/ollama-models
    type: DirectoryOrCreate
